API tests fail when flag off due to method not being found
Remove tests for @RequiresFlagsDisabled(com.android.permission.flags.Flags.FLAG_CROSS_USER_ROLE_ENABLED) due to methods not existing in image and throwing NoSuchMethodError and not making it to the IllegalStateException throw

LOW_COVERAGE_REASON=TEST_ONLY
Relnote: n/a
Bug: 387945959
Flag: TEST_ONLY
Test: atest RoleManagerTest
Change-Id: Iaf5cf9936e0a0d75e36846ebc6743076feb0d5b4